### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by yeltayev22** [alexejk/go-xmlrpc#37]
Is there any solution to handle errors? I want to get specific error codes after making a call. In my case to check for 401 (unauthorized) and update the tokens accordingly.
@alexejk

**Comment by alexejk** [comment]
Hi @yeltayev22, you should be able to provide a customized `*http.Client` with the custom `RoundTripper` implementation. This would then allow you to make requests in a way you want and intercept any errors before they are returned all the way to the library (and potentially apply a retry with custom tokens).

I intentionally left this on a basic level and opened the option to set a custom `*http.Client` via `NewClient(endpoint string, HttpClient(*http.Client))` as from the way I see there are too many cases to cover to make it flexible enough for most needs.

**Comment by alexejk** [comment]
As there has been no feedback or response, I assume this isn't a problem anymore and will therefore close this issue.

If you need any additional help, please feel free to reach out!
