### ISSUE TITLE
Need a script to transform xml request to RPC call struct

### ISSUE THREAD

**Issue by yangyao** [alexejk/go-xmlrpc#47]
And also transform xml response to go struct

After a lot of struggle, I found the following pattern. ( Notice the green text

![image](https://user-images.githubusercontent.com/5866775/144530496-053c4b40-514c-416d-b169-5ca523ac3275.png)

**Comment by yangyao** [comment]
For this type of struct . not able to transform 

```
<methodResponse>
	<params>
		<param>
			<value>
				<struct>
					<member>
						<name>2</name>
						<value>
							<struct>
								<member>
									<name>tag_id</name>
									<value>
										<string>2</string>
									</value>
								</member>
								<member>
									<name>name</name>
									<value>
										<string>product01-tag02</string>
									</value>
								</member>
							</struct>
						</value>
					</member>
				</struct>
			</value>
		</param>
	</params>
</methodResponse>
```


&struct {
    2 : struct {
        TagId : string,
        Name : string 
    }
}

not able to define this kind of struct ..

**Comment by alexejk** [comment]
This should now be possible with v0.4.0 by using `xmlrpc` tag on fields. Specifically, you can remap the field with something like this:

```
&struct {
    Two: struct {
        TagId : string,
        Name : string 
    } `xmlrpc:"2"`
}
```
