### ISSUE TITLE
panic when fields not define on response struct

### ISSUE THREAD

**Issue by yangyao** [alexejk/go-xmlrpc#48]
When you miss some field on the response struct , it will fail with this message :

reading body failed decoding array item at index 0: cannot find field 'CouponCode' on struct

when xmlrpc server add new fields ,the program will panic.

https://github.com/alexejk/go-xmlrpc/blob/master/decode.go#L142

**Comment by alexejk** [comment]
Could you please provide a sample to reproduce this on? I'll take a look at the issue

**Comment by alexejk** [comment]
It's now possible as of v0.4.0 to set `SkipUnknownFields(true)` option to avoid this issue. However there was never a panic but an error returned.
